name: "Build FBX2GLTF for Windows 10."
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install conan
        run: |
          pip install --upgrade conan
        shell: bash

      - name: Setup conan profile
        run: |
          conan profile new default --detect
          conan profile show default
        shell: bash

      - name: Setup filter.lfs.required
        run: |
          git config --global filter.lfs.required false
        shell: bash

      - name: Setup filter.lfs.smudge
        run: |
          git config --global filter.lfs.smudge "git-lfs smudge --skip %f"
        shell: bash

      - name: Setup filter.lfs.process
        run: |
          git config --global filter.lfs.process "git-lfs filter-process --skip"
        shell: bash
        
      - name: Curl sdk
        run: |
          curl -O -L "https://github.com/V-Sekai/FBXSDK-Windows/archive/refs/tags/2020.2.zip"
        shell: cmd
            
      - name: install 7z extract
        run: |
          7z x 2020.2.zip
        shell: cmd

      - name: move
        run: |
          mkdir -p sdk
          mv ./FBXSDK-Windows-2020.2/sdk ./sdk
        shell: bash

      - name: Decompress sdk
        run: |
          zstd -d -r --rm ./FBX2glTF/sdk
        shell: cmd

      - name: Add conan remote
        run: |
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        shell: cmd

      - name: Conan install
        run: |
          conan install . -i build -s build_type=Release -s compiler="Visual Studio" --build fmt --build libiconv --build=libxml2 --build=zlib --build=bzip
        shell: cmd

      - name: Conan build
        run: |
          conan build -bf build .
        shell: cmd

        - uses: actions/upload-artifact@v2
        with:
          name: FBX2glTF-windows-x64.exe
          path: FBX2glTF/build/Release/FBX2glTF.exe
